imports:
- path: service_account.jinja
- path: iam_policy.jinja
- path: bucket_acl.jinja
- path: ubuntu_vm.jinja
- path: cloud_function.jinja

resources:
- name: pr-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private
    
- name: pr-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-east5-c
    open_external: true

- name: pr-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pr }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pr}},"LEVEL_NAME":{{level_name_pr}}}

- name: pr-f-check
  type: cloud_function.jinja
  properties:
    region: europe-west1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pr }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables:  {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pr}},"LEVEL_NAME":{{level_name_pr}}}


- name: pd1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: pd1-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers  
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd1}},"LEVEL_NAME":{{level_name_pd1}}}

- name: pd1-f-check
  type: cloud_function.jinja
  properties:
    region: europe-west1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd1}},"LEVEL_NAME":{{level_name_pd1}}}


- name: pd2-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-east5-c
    open_external: true

- name: pd2-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_pd2 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd2}},"LEVEL_NAME":{{level_name_pd2}}}

- name: pd2-f-check
  type: cloud_function.jinja
  properties:
    region: europe-west1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_pd2 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_pd2}},"LEVEL_NAME":{{level_name_pd2}}}

- name: ct1-bucket
  type: bucket_acl.jinja
  properties:
    nonce: {{ nonce }}
    predefined_acl: private

- name: ct1-instance
  type: ubuntu_vm.jinja
  properties:
    zone: us-east5-c
    open_external: true

- name: ct1-f-access
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funca_upload_url_ct1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct1}},"LEVEL_NAME":{{level_name_ct1}}}

- name: ct1-f-check
  type: cloud_function.jinja
  properties:
    region: europe-west1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_ct1 }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}},"RESOURCE_PREFIX":{{resource_prefix_ct1}},"LEVEL_NAME":{{level_name_ct1}}}
- name: scores-f
  type: cloud_function.jinja
  properties:
    region: us-central1
    nonce: {{ nonce }}
    entry_point: main
    upload_url: {{ funcc_upload_url_scores }}
    policyBindings:
    - role: roles/cloudfunctions.invoker
      all_users: allusers 
    env_variables: {"NONCE":{{nonce}}, "LOGIN_USER":{{login_user}}}


- name: iam_policy
  type: iam_policy.jinja
  properties:
    bindings:
    - service_account_id: pr-f-access-{{nonce}}-sa
      role:
        name: roles/owner

    - service_account_id: pr-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd1-f-access-{{nonce}}-sa
      role:
        name: roles/storage.admin

    - service_account_id: pd1-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer


    - service_account_id: pd2-f-access-{{nonce}}-sa
      role:
        name: roles/compute.admin

    - service_account_id: pd2-f-check-{{nonce}}-sa
      role:
        name: roles/iam.roleViewer


    - service_account_id: ct1-f-access-{{nonce}}-sa
      role:
        name: roles/owner

    - service_account_id: ct1-f-check-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy

    - service_account_id: scores-f-{{nonce}}-sa
      role:
        name: custom
        custom_nonce: {{ nonce }}
        permissions:
        - iam.roles.list
        - resourcemanager.projects.getIamPolicy